name: Cypress Tests

on: [push]

jobs:
  cypress-concurrent:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: install
        run: yarn

      - name: Run
        run: yarn cy:para

  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: install
        run: yarn

      - name: Run
        run: yarn cy:solo
